// <auto-generated />
using System;
using Dr.meow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dr.meow.Migrations
{
    [DbContext(typeof(DrMeowDbContext))]
    [Migration("20260309085439_UpdateSeedDataAndRoles")]
    partial class UpdateSeedDataAndRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dr.meow.Models.RequestForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AiPass")
                        .HasColumnType("bit");

                    b.Property<string>("AiReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AiReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedEngineerId")
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrossReviewerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrossReviewerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineerTestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewAcceptanceContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewAcceptanceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ReviewBenefitManDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReviewBenefitRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReviewRejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewSatisfactionNeed")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewSatisfactionOverall")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewSatisfactionStability")
                        .HasColumnType("int");

                    b.Property<string>("ReviewSecurityAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestForms");
                });

            modelBuilder.Entity("Dr.meow.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "工程師"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Team1主管"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Team2主管"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "最高階主管"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "一般組員"
                        });
                });

            modelBuilder.Entity("Dr.meow.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Account = "enginee",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 3, 9, 16, 54, 38, 827, DateTimeKind.Local).AddTicks(2395),
                            Email = "dept@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 2,
                            Account = "team1boss",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 3, 9, 16, 54, 38, 827, DateTimeKind.Local).AddTicks(2415),
                            Email = "team1@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 3,
                            Account = "team2boss",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 3, 9, 16, 54, 38, 827, DateTimeKind.Local).AddTicks(2417),
                            Email = "team2@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 4,
                            Account = "superboss",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 3, 9, 16, 54, 38, 827, DateTimeKind.Local).AddTicks(2419),
                            Email = "super@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 5,
                            Account = "gmember",
                            AccountType = "User",
                            CreatedAt = new DateTime(2026, 3, 9, 16, 54, 38, 827, DateTimeKind.Local).AddTicks(2422),
                            Email = "super@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        });
                });

            modelBuilder.Entity("Dr.meow.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 5
                        });
                });

            modelBuilder.Entity("Dr.meow.Models.Vulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dependency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FoundDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImpactLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecoveryPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScheduledTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TicketCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Vulnerability");
                });

            modelBuilder.Entity("Dr.meow.Models.UserRole", b =>
                {
                    b.HasOne("Dr.meow.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dr.meow.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dr.meow.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Dr.meow.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
