// <auto-generated />
using System;
using Dr.meow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dr.meow.Migrations
{
    [DbContext(typeof(DrMeowDbContext))]
    [Migration("20260509081727_AddEvaluationFields")]
    partial class AddEvaluationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dr.meow.Models.AiConsultLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AiConsultLogs");
                });

            modelBuilder.Entity("Dr.meow.Models.Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Dr.meow.Models.RequestAiDetail", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int?>("AiOverallScore")
                        .HasColumnType("int");

                    b.Property<string>("AiReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AiRequirementScore")
                        .HasColumnType("int");

                    b.Property<decimal?>("AiRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AiReviewComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AiSavedManDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AiStabilityScore")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsITRelated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefinedDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefinedTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("RequestAiDetails");
                });

            modelBuilder.Entity("Dr.meow.Models.RequestAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestAuditLogs");
                });

            modelBuilder.Entity("Dr.meow.Models.RequestStatus", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StatusId");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = (byte)0,
                            Description = "等待 AI 分析",
                            StatusName = "PendingAI"
                        },
                        new
                        {
                            StatusId = (byte)1,
                            Description = "等待主管審核",
                            StatusName = "PendingReview"
                        },
                        new
                        {
                            StatusId = (byte)2,
                            Description = "工程師開發中",
                            StatusName = "InDevelopment"
                        },
                        new
                        {
                            StatusId = (byte)3,
                            Description = "需求已結案",
                            StatusName = "Completed"
                        },
                        new
                        {
                            StatusId = (byte)4,
                            Description = "需求已被拒絕",
                            StatusName = "Rejected"
                        });
                });

            modelBuilder.Entity("Dr.meow.Models.RequestTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedBenefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpectedCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RequestType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("SystemCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.ToTable("RequestTickets");
                });

            modelBuilder.Entity("Dr.meow.Models.RequestUserInput", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Benefit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("RequestUserInputs");
                });

            modelBuilder.Entity("Dr.meow.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "工程師"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Team1主管"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Team2主管"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "最高階主管"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Team1組員"
                        },
                        new
                        {
                            RoleId = 6,
                            RoleName = "Team2組員"
                        });
                });

            modelBuilder.Entity("Dr.meow.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Account = "enginee",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 5, 9, 16, 17, 26, 671, DateTimeKind.Local).AddTicks(1248),
                            Email = "dept@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 2,
                            Account = "team1boss",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 5, 9, 16, 17, 26, 671, DateTimeKind.Local).AddTicks(1250),
                            Department = "Team1",
                            Email = "team1@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 3,
                            Account = "team2boss",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 5, 9, 16, 17, 26, 671, DateTimeKind.Local).AddTicks(1252),
                            Department = "Team2",
                            Email = "team2@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 4,
                            Account = "superboss",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 5, 9, 16, 17, 26, 671, DateTimeKind.Local).AddTicks(1254),
                            Email = "super@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 5,
                            Account = "gmember1",
                            AccountType = "User",
                            CreatedAt = new DateTime(2026, 5, 9, 16, 17, 26, 671, DateTimeKind.Local).AddTicks(1256),
                            Department = "Team1",
                            Email = "user1@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 6,
                            Account = "gmember2",
                            AccountType = "User",
                            CreatedAt = new DateTime(2026, 5, 9, 16, 17, 26, 671, DateTimeKind.Local).AddTicks(1257),
                            Department = "Team2",
                            Email = "user2@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        });
                });

            modelBuilder.Entity("Dr.meow.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 6
                        });
                });

            modelBuilder.Entity("Dr.meow.Models.Vulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Dependency")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpactLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LastReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("RecoveryPlan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SystemCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TestPlan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TicketCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.ToTable("Vulnerability");
                });

            modelBuilder.Entity("Dr.meow.Models.VulnerabilityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VulnerabilityId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("VulnerabilityId");

                    b.ToTable("VulnerabilityLogs");
                });

            modelBuilder.Entity("Dr.meow.Models.RequestAiDetail", b =>
                {
                    b.HasOne("Dr.meow.Models.RequestTicket", "RequestTicket")
                        .WithOne("AiDetail")
                        .HasForeignKey("Dr.meow.Models.RequestAiDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestTicket");
                });

            modelBuilder.Entity("Dr.meow.Models.RequestAuditLog", b =>
                {
                    b.HasOne("Dr.meow.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dr.meow.Models.RequestTicket", "RequestTicket")
                        .WithMany("AuditLogs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestTicket");
                });

            modelBuilder.Entity("Dr.meow.Models.RequestTicket", b =>
                {
                    b.HasOne("Dr.meow.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dr.meow.Models.RequestUserInput", b =>
                {
                    b.HasOne("Dr.meow.Models.RequestTicket", "RequestTicket")
                        .WithOne("UserInput")
                        .HasForeignKey("Dr.meow.Models.RequestUserInput", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestTicket");
                });

            modelBuilder.Entity("Dr.meow.Models.UserRole", b =>
                {
                    b.HasOne("Dr.meow.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dr.meow.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dr.meow.Models.Vulnerability", b =>
                {
                    b.HasOne("Dr.meow.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Dr.meow.Models.VulnerabilityLog", b =>
                {
                    b.HasOne("Dr.meow.Models.Vulnerability", null)
                        .WithMany()
                        .HasForeignKey("VulnerabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dr.meow.Models.RequestTicket", b =>
                {
                    b.Navigation("AiDetail")
                        .IsRequired();

                    b.Navigation("AuditLogs");

                    b.Navigation("UserInput")
                        .IsRequired();
                });

            modelBuilder.Entity("Dr.meow.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Dr.meow.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
