// <auto-generated />
using System;
using Dr.meow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Dr.meow.Migrations
{
    [DbContext(typeof(DrMeowDbContext))]
    partial class DrMeowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Dr.meow.Models.RequestUserInput", b =>
            {
                b.Property<int>("RequestId");

                b.Property<string>("Benefit");

                b.Property<string>("Contact")
                    .IsRequired();

                b.Property<string>("Department")
                    .IsRequired();

                b.Property<string>("Description")
                    .IsRequired();

                b.Property<DateTime?>("ExpectedDate");

                b.Property<string>("Note");

                b.Property<string>("Priority")
                    .IsRequired();

                b.Property<string>("RequestType")
                    .IsRequired();

                b.Property<string>("Role")
                    .IsRequired();

                b.Property<string>("SystemCategory")
                    .IsRequired();

                b.HasKey("RequestId");

                b.ToTable("RequestUserInputs");
            });

            modelBuilder.Entity("Dr.meow.Models.RequestTicket", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<DateTime>("CreatedAt");

                b.Property<string>("Description")
                    .IsRequired();

                b.Property<int>("RequesterId");

                b.Property<byte>("Status");

                b.Property<string>("TicketNumber")
                    .IsRequired();

                b.Property<string>("Title")
                    .IsRequired();

                b.Property<DateTime>("UpdatedAt");

                b.HasKey("Id");

                b.ToTable("RequestTickets");
            });

            modelBuilder.Entity("Dr.meow.Models.User", b =>
            {
                b.Property<int>("UserId")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Account");

                b.Property<string>("AccountType")
                    .IsRequired();

                b.Property<DateTime>("CreatedAt");

                b.Property<string>("Department");

                b.Property<string>("Email")
                    .IsRequired();

                b.Property<bool>("IsActive");

                b.Property<string>("PasswordHash");

                b.HasKey("UserId");

                b.ToTable("Users");
            });
        }
    }
}