// <auto-generated />
using System;
using Dr.meow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Dr.meow.Migrations
{
    [DbContext(typeof(DrMeowDbContext))]
    partial class DrMeowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Dr.meow.Models.RequestUserInput", b =>
            {
                b.Property<int>("RequestId");

                b.Property<string>("Benefit");

                b.Property<string>("Contact")
                    .IsRequired();

                b.Property<string>("Department")
                    .IsRequired();

                b.Property<string>("Description")
                    .IsRequired();

                b.Property<DateTime?>("ExpectedDate");

                b.Property<string>("Note");

                b.Property<string>("Priority")
                    .IsRequired();

                b.Property<string>("RequestType")
                    .IsRequired();

                b.Property<string>("Role")
                    .IsRequired();

                b.Property<string>("SystemCategory")
                    .IsRequired();

                b.HasKey("RequestId");

<<<<<<< HEAD
                b.ToTable("RequestUserInputs");
            });
=======
                    b.ToTable("RequestUserInputs");
                });

            modelBuilder.Entity("Dr.meow.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "工程師"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Team1主管"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Team2主管"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "最高階主管"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Team1組員"
                        },
                        new
                        {
                            RoleId = 6,
                            RoleName = "Team2組員"
                        });
                });

            modelBuilder.Entity("Dr.meow.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Account = "enginee",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 3, 30, 20, 49, 34, 611, DateTimeKind.Local).AddTicks(9442),
                            Email = "dept@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 2,
                            Account = "team1boss",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 3, 30, 20, 49, 34, 611, DateTimeKind.Local).AddTicks(9446),
                            Department = "Team1",
                            Email = "team1@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 3,
                            Account = "team2boss",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 3, 30, 20, 49, 34, 611, DateTimeKind.Local).AddTicks(9448),
                            Department = "Team2",
                            Email = "team2@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 4,
                            Account = "superboss",
                            AccountType = "Admin",
                            CreatedAt = new DateTime(2026, 3, 30, 20, 49, 34, 611, DateTimeKind.Local).AddTicks(9451),
                            Email = "super@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 5,
                            Account = "gmember1",
                            AccountType = "User",
                            CreatedAt = new DateTime(2026, 3, 30, 20, 49, 34, 611, DateTimeKind.Local).AddTicks(9453),
                            Department = "Team1",
                            Email = "user1@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        },
                        new
                        {
                            UserId = 6,
                            Account = "gmember2",
                            AccountType = "User",
                            CreatedAt = new DateTime(2026, 3, 30, 20, 49, 34, 611, DateTimeKind.Local).AddTicks(9456),
                            Department = "Team2",
                            Email = "user2@drmeow.com",
                            IsActive = true,
                            PasswordHash = "123456"
                        });
                });

            modelBuilder.Entity("Dr.meow.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 6
                        });
                });

            modelBuilder.Entity("Dr.meow.Models.Vulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Dependency")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpactLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LastReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("RecoveryPlan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SystemCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TestPlan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TicketCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.ToTable("Vulnerability");
                });

            modelBuilder.Entity("Dr.meow.Models.VulnerabilityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VulnerabilityId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("VulnerabilityId");

                    b.ToTable("VulnerabilityLogs");
                });

            modelBuilder.Entity("Dr.meow.Models.RequestAiDetail", b =>
                {
                    b.HasOne("Dr.meow.Models.RequestTicket", "RequestTicket")
                        .WithOne("AiDetail")
                        .HasForeignKey("Dr.meow.Models.RequestAiDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestTicket");
                });

            modelBuilder.Entity("Dr.meow.Models.RequestAuditLog", b =>
                {
                    b.HasOne("Dr.meow.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dr.meow.Models.RequestTicket", "RequestTicket")
                        .WithMany("AuditLogs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestTicket");
                });
>>>>>>> parent of b807ace (調整UI：移除sidebar、置中使用者顧問中心、header新增查看表單)

            modelBuilder.Entity("Dr.meow.Models.RequestTicket", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<DateTime>("CreatedAt");

                b.Property<string>("Description")
                    .IsRequired();

                b.Property<int>("RequesterId");

                b.Property<byte>("Status");

                b.Property<string>("TicketNumber")
                    .IsRequired();

                b.Property<string>("Title")
                    .IsRequired();

                b.Property<DateTime>("UpdatedAt");

                b.HasKey("Id");

                b.ToTable("RequestTickets");
            });

            modelBuilder.Entity("Dr.meow.Models.User", b =>
            {
                b.Property<int>("UserId")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Account");

                b.Property<string>("AccountType")
                    .IsRequired();

                b.Property<DateTime>("CreatedAt");

                b.Property<string>("Department");

                b.Property<string>("Email")
                    .IsRequired();

                b.Property<bool>("IsActive");

                b.Property<string>("PasswordHash");

                b.HasKey("UserId");

                b.ToTable("Users");
            });
        }
    }
}