<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>30e528cc-c0d1-4d60-9a89-74c9b11dc332</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Pages\NewFolder\**" />
	  <Content Remove="Pages\NewFolder\**" />
	  <EmbeddedResource Remove="Pages\NewFolder\**" />
	  <None Remove="Pages\NewFolder\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Models\Notifications.cs" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="C:\Users\10932\Downloads\程式碼\consult.css" Link="consult.css" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EPPlus" Version="6.1.0" />
		<PackageReference Include="Hangfire" Version="1.8.23" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
		<PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.13" />
		<PackageReference Include="Microsoft.SemanticKernel" Version="1.74.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
	</ItemGroup>

</Project>